Japanese localization
soramitsu/fearless-iOS pull request #1016
Opened 2023-06-16 09:48 UTC by bnsports

2023-06-16 11:35 UTC, DRadmir requested changes

2023-06-16 11:35 UTC, DRadmir commented on fearless/Common/Helpers/AssetBalanceFormatterFactory.swift
> +enum FormatterLocale {
I suggest create init from Locale.identifire

2023-06-16 11:35 UTC, DRadmir commented on fearless/Common/Helpers/AmountFormatterFactory.swift
> +            abbreviations = [
It is advisable create struct with abbreviations arrays in other file
struct Abbreviations {
static let japanese = []
static let usual = []
}

2023-06-16 11:35 UTC, DRadmir commented on fearless/Modules/Staking/SelectValidatorsFlow/RecommendedValidatorList/Flow/Pool/RecommendedValidatorListPoolViewModelFactory.swift
> +            ""
please check this

2023-06-16 11:35 UTC, DRadmir commented on fearless/Modules/Staking/SelectValidatorsFlow/RecommendedValidatorList/Flow/Relaychain/RecommendedValidatorListRelaychainViewModelFactory.swift
> +            ""
please check this

2023-06-16 11:35 UTC, DRadmir commented on fearless/Modules/Staking/StakingPayoutConfirmation/ViewModel/StakingPayoutConfirmViewModelFactory.swift
> +//                .commonAccount(preferredLanguages: locale.rLanguages)
comments

2023-06-29 08:00 UTC, Viscount88 approved these changes

2023-06-29 08:04 UTC, closed without merging