Feature/eth api
soramitsu/fearless-iOS pull request #1080
Opened 2023-07-28 07:45 UTC by bnsports

2023-07-29 09:40 UTC, DRadmir requested changes
The main point need think about Import Web3 with BigInt
Also lets discuss about create dependency for send module

2023-07-29 09:40 UTC, DRadmir commented on fearless/CoreLayer/OperationFactory/BlockExplorer/History/Main/HistoryOperationFactory.swift
> +            return GiantsquidHistoryOperationFactory(txStorage: txStorage)
why with none case we return GiantsquidHistoryOperationFactory? Perhaps should return nil?

2023-07-29 09:40 UTC, DRadmir commented on fearless/CoreLayer/OperationFactory/BlockExplorer/History/Staking/ParachainHistoryOperationFactory.swift
> +            return ParachainSubsquidHistoryOperationFactory(url: blockExplorer?.url)
this is correct?

2023-07-29 09:40 UTC, DRadmir commented on fearless/CoreLayer/OperationFactory/BlockExplorer/Rewards/RewardOperationFactory.swift
> +            return GiantsquidRewardOperationFactory(url: blockExplorer?.url, chain: chain)
this is correct?

2023-07-29 09:40 UTC, DRadmir commented on fearless/Modules/NewWallet/ChainAccount/ChainAccountInteractor.swift
> +                guard let strongSelf = self else {
use strongSelf for didReceive also

2023-07-29 09:40 UTC, DRadmir commented on fearless/Modules/NewWallet/ChainAccount/ChainAccountInteractor.swift
> +                self?.walletBalanceSubscriptionAdapter.subscribeChainAssetBalance(
use strongSelf

2023-07-29 09:40 UTC, DRadmir commented on fearless/Modules/NewWallet/ChainAssetList/ChainAssetListAssembly.swift
> +        let operationQueue = OperationQueue()
I don't see where use operation queue

2023-07-29 09:40 UTC, DRadmir commented on fearless/Modules/Send/SendDependencyContainer.swift
> +                usedRuntimePaths: [:],
need send modules which used for send

2023-07-29 09:40 UTC, DRadmir commented on fearless/Modules/Send/SendDependencyContainer.swift
> +    private func createTransferService(for chainAsset: ChainAsset) async throws -> TransferServiceProtocol {
lets discuss this solution

2023-07-29 09:40 UTC, DRadmir commented on fearless/Modules/Send/SendInteractor.swift
> +extension SendInteractor: TransferFeeEstimationListener {
perhaps be better update func didReceiveFee(fee: BigUInt) with func didReceiveFee(fee: Result<BigUInt, Error?>)

2023-07-29 09:40 UTC, DRadmir commented on fearless/Modules/Send/SendInteractor.swift
> +        output?.didReceiveFee(result: .failure(feeError))
main thread use in presenter?

2023-08-01 04:14 UTC, bnsports commented on fearless/ApplicationLayer/Ethereum/EthereumBalanceSubscription.swift
> +        DispatchQueue.main.async { [weak self] in
because timer only works from main thread

2023-08-01 05:02 UTC, bnsports commented on fearless/ApplicationLayer/Services/TransferService/TransferService.swift
> +            accessList: [:],
yes

2023-08-01 05:02 UTC, bnsports commented on fearless/ApplicationLayer/Services/TransferService/TransferService.swift
> +        let rawTransaction = try tx.sign(with: privateKey, chainId: EthereumQuantity(quantity: chainIdValue))
because chainId parameter has type EthereumQuantity

2023-08-01 05:02 UTC, bnsports commented on fearless/ApplicationLayer/Services/TransferService/TransferService.swift
> +        let transferGasLimit = EthereumQuantity(quantity: 500_000)
fixed

2023-08-01 05:04 UTC, bnsports commented on fearless/ApplicationLayer/Services/TransferService/TransferService.swift
> +            accessList: [:],
yes

2023-08-01 05:08 UTC, bnsports commented on fearless/Common/Extension/ChainAsset+Eth.swift
> +extension ChainModel {
because we doensn't need to store connection like substrate chains do it

2023-08-01 05:12 UTC, bnsports commented on fearless/Common/Extension/Wallet/AssetTransactionData+AlchemyHistory.swift
> +        chain _: ChainModel,
protocol method

2023-08-01 05:13 UTC, bnsports commented on fearless/Common/Extension/Wallet/AssetTransactionData+EtherscanHistory.swift
> +        chain _: ChainModel,
protocol method

2023-08-01 05:25 UTC, bnsports commented on fearless/Common/Model/ChainRegistry/ChainAssetModel.swift
> +class ChainAssetModel: Codable {
then it will be removed during merge

2023-08-01 06:16 UTC, bnsports commented on fearless/CoreLayer/OperationFactory/BlockExplorer/Rewards/RewardOperationFactory.swift
> +            return GiantsquidRewardOperationFactory(url: blockExplorer?.url, chain: chain)
tech debt

2023-08-01 06:22 UTC, bnsports commented on fearless/Modules/Send/SendDependencyContainer.swift
> +                usedRuntimePaths: [:],
it works fine

2023-08-01 06:24 UTC, bnsports commented on fearless/ApplicationLayer/Alchemy/Model/Request/AlchemyHistoryRequest.swift
> +        fromBlock: AlchemyHistoryBlockFilter? = .hex(value: "0x0"),
it's 0 represented in hex. first one block by default

2023-08-11 11:34 UTC, closed without merging