Deprecated controller stash accounts
soramitsu/fearless-iOS pull request #1094
Opened 2023-08-24 08:30 UTC by Viscount88

2023-08-24 09:52 UTC, bnsports requested changes

2023-08-24 09:52 UTC, bnsports commented on fearless/Common/Services/DeprecatedControllerStashAccountCheckService.swift
> +final class DeprecatedControllerStashAccountCheckService {
service should be incapsulated by using protocol

2023-08-24 09:52 UTC, bnsports commented on fearless/Modules/Staking/ControllerAccount/View/ControllerAccountViewLayout.swift
> +            .stakingControllerDeprecatedDescription("this", preferredLanguages: locale.rLanguages)
as far I remember there should be network name

2023-08-24 09:52 UTC, bnsports commented on fearless/Common/Services/DeprecatedControllerStashAccountCheckService.swift
> +    func checkAccountDeprecations() async throws -> DeprecatedAccountIssue? {
it's better to pass wallet as argument, service should be stateless

2023-08-24 09:52 UTC, bnsports commented on fearless/Common/Services/DeprecatedControllerStashAccountCheckService.swift
> +        completionBlock: @escaping (Bool) -> Void
you are combine 2 different approaches: closures and await-async

2023-08-24 09:52 UTC, bnsports commented on fearless/Common/Services/DeprecatedControllerStashAccountCheckService.swift
> +            )) == true
sure? it looks like you should check for 'false' instead

2023-08-24 09:52 UTC, bnsports commented on fearless/Common/Services/DeprecatedControllerStashAccountCheckService.swift
> +        if let caIssue = caIssueChainAssets.first {
always false because you are fill caIssueChainAssets in async

2023-08-24 09:52 UTC, bnsports commented on fearless/Modules/WalletMainContainer/WalletMainContainerInteractor.swift
> +                    DispatchQueue.main.async {
inside task you can use MainActor

2023-08-24 11:08 UTC, DRadmir requested changes

2023-08-24 11:08 UTC, DRadmir commented on fearless/Common/Services/DeprecatedControllerStashAccountCheckService.swift
> +    func checkAccountDeprecations(wallet _: MetaAccountModel) async throws -> DeprecatedAccountIssue? {
1. wallet unused
2. Move this protocol method above private methods

2023-09-05 02:15 UTC, bnsports requested changes

2023-09-05 02:15 UTC, bnsports commented on fearless/Modules/WalletMainContainer/WalletMainContainerPresenter.swift
> +            DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
can we avoid using this ?

2023-09-05 02:15 UTC, bnsports commented on fearless/Common/Services/DeprecatedControllerStashAccountCheckService.swift
>          print("define deprecated chains finished")
remove print please

2023-09-05 02:15 UTC, bnsports commented on fearless/Common/Services/DeprecatedControllerStashAccountCheckService.swift
> +    func checkStashItems() async throws -> [StashItem] {
this function actually fetch stash items, not check it

2023-09-07 07:40 UTC, merged