Feature/sora staking rewards
soramitsu/fearless-iOS pull request #1136
Opened 2023-10-23 10:27 UTC by bnsports

2023-10-23 10:50 UTC, Viscount88 approved these changes

2023-11-07 04:49 UTC, DRadmir requested changes

2023-11-07 04:49 UTC, DRadmir commented on fearless/Common/Services/PayoutRewardsService/SoraSubsquidPayoutValidatorForNominatorFactory.swift
> +            var request = URLRequest(url: self.url)
use weak self

2023-11-07 04:49 UTC, DRadmir commented on fearless/Common/Services/PayoutRewardsService/ValidatorPayoutInfoFactory.swift
> +    let chainAsset: ChainAsset
private

2023-11-07 04:49 UTC, DRadmir commented on fearless/CoreLayer/OperationFactory/BlockExplorer/Rewards/SoraRewardOperationFactory.swift
> +            guard let url = self?.url else {
Use strongSelf

2023-11-07 04:49 UTC, DRadmir commented on fearless/CoreLayer/OperationFactory/BlockExplorer/Rewards/SoraRewardOperationFactory.swift
> +                SubqueryResponse<GiantsquidResponseData>.self,
Create response for Giantsquid

2023-11-07 05:10 UTC, DRadmir approved these changes

2023-11-07 08:10 UTC, merged