pending rewards fee in utility token
soramitsu/fearless-iOS pull request #1149
Opened 2023-11-09 08:32 UTC by bnsports

2023-11-09 08:33 UTC, DRadmir approved these changes

2023-11-09 08:35 UTC, Viscount88 requested changes

2023-11-09 08:35 UTC, Viscount88 commented on fearless/Modules/Staking/StakingPayoutConfirmation/StakingPayoutConfirmationPresenter.swift
> +    private var priceData: [PriceData] = []
priceDatas?

2023-11-10 04:43 UTC, Viscount88 approved these changes

2023-11-10 04:46 UTC, merged