NFT Main module + logic
soramitsu/fearless-iOS pull request #1160
Opened 2023-11-16 06:04 UTC by Viscount88

2023-11-17 06:17 UTC, DRadmir requested changes

2023-11-22 04:30 UTC, Viscount88 commented on fearless/CoreLayer/OperationFactory/NFT/AlchemyNFTOperationFactory.swift
> +                    metadata: nil,
fixed

2023-11-22 04:31 UTC, Viscount88 commented on fearless/ApplicationLayer/Services/NFT/Ethereum/AlchemyNftFetchingService.swift
> +        let nfts = await withThrowingTaskGroup(of: [NFT]?.self) { [weak self] _ in
fixed

2023-11-22 04:31 UTC, Viscount88 commented on fearless/CoreLayer/OperationFactory/NFT/AlchemyNFTOperationFactory.swift
> +        dependingOn remoteOperation: BaseOperation<AlchemyOwnedNftsResponse>,
discussed

2023-11-22 04:48 UTC, Viscount88 commented on fearless/Modules/NFT/MainNftContainer/MainNftContainerRouter.swift
> +    func showFilters(from _: ControllerBackedProtocol?) {}
fixed

2023-12-27 11:45 UTC, closed without merging