Feature/reef support
soramitsu/fearless-iOS pull request #1176
Opened 2023-12-19 12:08 UTC by bnsports

2023-12-19 16:50 UTC, DRadmir requested changes

2023-12-19 16:50 UTC, DRadmir commented on fearless/Common/Services/RemoteSubscription/StakingAccountSubscription/StakingAccountSubscriptionV14.swift
> +        mutex.lock()
please check, perhaps you can use super method?

2023-12-19 16:50 UTC, DRadmir commented on fearless/Common/Services/RemoteSubscription/StakingAccountSubscription/StakingAccountSubscriptionV14.swift
> +        mutex.lock()
please check, perhaps you can use super method?

2023-12-19 16:50 UTC, DRadmir commented on fearless/Common/Substrate/CallFactory/SubstrateCallFactoryDefault.swift
> +        let args = TransferCall(dest: .indexedString(receiver), value: amount, currencyId: nil)
Does it work successfully with 14 metadata?

2023-12-19 16:50 UTC, DRadmir commented on fearless/Common/Substrate/Calls/BondCall.swift
> +    enum CodingKeys: String, CodingKey {
all changes below in this file compatible with 13 and 14 metadata?

2023-12-19 16:50 UTC, DRadmir commented on fearless/Common/Substrate/Types/AccountInfo.swift
> +extension AccountInfo: ScaleDecodable {
please check, needed this extensions?

2023-12-19 16:50 UTC, DRadmir commented on fearless/Common/Substrate/Types/Nomination.swift
> +        } catch {
nice

2023-12-19 16:50 UTC, DRadmir commented on fearless/Common/Substrate/Types/SuperIdentity.swift
> +        print("success")
without this print will not work

2023-12-19 16:50 UTC, DRadmir commented on fearless/CoreLayer/OperationFactory/BlockExplorer/History/Main/ReefSubsquidHistoryOperationFactory.swift
> +//        if filters.contains(where: { $0.type == .other && $0.selected }) {
comments

2023-12-19 16:50 UTC, DRadmir commented on fearless/CoreLayer/OperationFactory/BlockExplorer/History/Staking/ParachainHistoryOperationFactory.swift
> +        case .alchemy, .etherscan, .reef:
why?

2023-12-19 16:50 UTC, DRadmir commented on fearless/CoreLayer/OperationFactory/BlockExplorer/Rewards/ReefRewardOperationFactory.swift
> +final class ReefRewardOperationFactory {
I guess this doesn't work?

2023-12-19 16:50 UTC, DRadmir commented on fearless/Modules/NewWallet/WalletSendConfirm/WalletSendConfirmInteractor.swift
> +                    self?.runtimeItems = items
what if save map?

2023-12-19 16:50 UTC, DRadmir commented on fearless/Modules/Send/SendInteractor.swift
> +                    self?.runtimeItems = items
what if save map?

2023-12-19 16:50 UTC, DRadmir commented on fearless/Modules/Staking/Operations/IdentityOperationFactory.swift
> +        let keyParams: () throws -> [AccountAddress] = {
Does successful work with 14 metadata?

2023-12-19 16:50 UTC, DRadmir commented on fearless/Resources/chains.json
discard changes?

2023-12-21 08:37 UTC, bnsports commented on fearless/Common/Network/BlockExplorer/Subsquid/ReefSubsquidHistory.swift
> +        []
not implemented yet

2023-12-28 11:04 UTC, DRadmir approved these changes

2023-12-28 11:08 UTC, DRadmir submitted a review, later dismissed

2023-12-28 11:56 UTC, DRadmir approved these changes

2023-12-28 12:04 UTC, merged