Feature/balance locks
soramitsu/fearless-iOS pull request #1208
Opened 2024-02-15 07:11 UTC by bnsports

2024-02-27 10:13 UTC, DRadmir requested changes

2024-02-27 10:13 UTC, DRadmir commented on fearless/Modules/BalanceLocksDetail/ViewModel/BalanceLocksDetailViewModelFactory.swift
> +        nil
check this method please

2024-02-27 10:13 UTC, DRadmir commented on fearlessTests/Modules/BalanceLocksDetail/BalanceLocksDetailTests.swift
> +import XCTest
Remove or implement

2024-03-01 05:14 UTC, bnsports commented on fearless/Modules/BalanceInfo/BalanceInfoDependencyContainer.swift
> +        let balanceLocksFetcher = try? BalanceLocksFetchingFactory.buildBalanceLocksFetcher(for: chainAsset)
no, it uses runtimeservice inside and it will be nil for ethereum chains. it's expected behaviour

2024-03-01 05:15 UTC, bnsports commented on fearless/Modules/BalanceLocksDetail/BalanceLocksDetailAssembly.swift
> +            let balanceLocksFetching = try? BalanceLocksFetchingFactory.buildBalanceLocksFetcher(for: chainAsset)
it will be nil for ethereum chains

2024-03-01 05:16 UTC, bnsports commented on fearless/Modules/BalanceLocksDetail/BalanceLocksDetailAssembly.swift
> +            let balanceLocksFetching = try? BalanceLocksFetchingFactory.buildBalanceLocksFetcher(for: chainAsset)
anyway refactored to return optional instrad of throws

2024-03-06 07:16 UTC, Viscount88 approved these changes

2024-03-06 07:23 UTC, DRadmir approved these changes

2024-03-06 07:24 UTC, merged