[#FLW-4461, #FLW-4462, #FLW-4464] Assets management
soramitsu/fearless-iOS pull request #1232
Opened 2024-04-02 07:16 UTC by DRadmir

2024-05-21 05:07 UTC, bnsports requested changes

2024-05-21 05:07 UTC, bnsports commented on fearless/Modules/NewWallet/ChainAssetList/ChainAssetListInteractor.swift
> +    var shouldRunManageAssetAnimate: Bool {
not right place for this code. should be inside some *Settings

2024-05-21 05:07 UTC, bnsports commented on fearless/Modules/NetworkManagment/NetworkManagmentInteractor.swift
> +    func didSelect(_ identifire: String) {
identifier

2024-05-21 05:07 UTC, bnsports commented on fearless/Modules/NetworkIssuesNotification/NetworkIssuesNotificationPresenter.swift
> +                let filtred = chains.filter { chain in
filtered

2024-05-21 05:07 UTC, bnsports commented on fearless/Modules/NetworkIssuesNotification/NetworkIssuesNotificationPresenter.swift
> +                let filtred = chains.filter { chain in
filtered

2024-05-21 08:06 UTC, DRadmir commented on fearless/ApplicationLayer/Services/Balance/RemoteSubscription/AccountInfoRemoteService.swift
> +        if chainAsset.chain.knownChainEquivalent == .genshiro {
exactly

2024-05-21 08:11 UTC, DRadmir commented on fearless/Common/Helpers/EthereumNodeFetching.swift
> +        let web3 = Web3(provider: provider, rpcId: 1)
correct

2024-05-21 09:05 UTC, DRadmir commented on fearless/Modules/AssetManagement/AssetManagementPresenter.swift
> +                let chainAssets = try await interactor.getAvailableChainAssets()
need for next line

2024-05-22 08:06 UTC, bnsports approved these changes

2024-05-22 08:10 UTC, merged