Feature/flw 4481 spm
soramitsu/fearless-iOS pull request #1258
Opened 2024-06-17 05:50 UTC by bnsports

2024-07-03 08:30 UTC, DRadmir requested changes

2024-07-03 08:30 UTC, DRadmir commented on fearless.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "branch" : "master",
please pay your attension what Web3 in Package has right version

2024-07-03 08:30 UTC, DRadmir commented on fearless/ApplicationLayer/Pricing/SoraSubqueryPriceFetcher.swift
> +        prices _: [SoraSubqueryPrice],
unused

2024-07-03 08:30 UTC, DRadmir commented on fearless/ApplicationLayer/Services/SoraFiatService/SoraFiatService.swift
> +        let queryOperation = SubqueryFiatInfoOperation<[FiatData]>(baseUrl: ApplicationConfig.shared.soraSubqueryUrl)
perhaps better use remote url?

2024-07-03 08:30 UTC, DRadmir commented on fearless/ApplicationLayer/Services/SoraFiatService/SubqueryFiatInfoOperation.swift
> +public final class SubqueryFiatInfoOperation<ResultType>: BaseOperation<ResultType> {
I believe what you can find the best solution. I suggest use async style instead operation

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Configs/ApplicationConfigs.swift
> +    var soraSubqueryUrl: URL {
will better use remote link

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/DataProvider/Sources/PriceDataSource.swift
> +//            let replacedFiatDayChange: [PriceData] = chainlinkPrices.compactMap { chainlinkPrice in
comment

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/DataProvider/Sources/PriceDataSource.swift
> +        guard let chain = chainAssets.first(where: { $0.chain.knownChainEquivalent == .soraMain })?.chain else {
can be combined with previous guard

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/DataProvider/Sources/PriceDataSource.swift
> +                guard let priceId = chainAsset.asset.priceId else {
combine guard

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Extension/Model/CryptoType+Extrinsic.swift
> +extension CryptoType {
should be removed?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Extension/UIKit/SkeletonRow+View.swift
> +        size _: CGSize
unused

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Extension/UIKit/SkeletonRow+View.swift
> +        SingleSkeleton(position: position, size: CGSize(width: 1, height: 1)).round()
maybe should use size from parameter?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Model/AssetVisibility.swift
> +// struct AssetVisibility: Codable, Equatable, Hashable, Identifiable {
comment

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Model/ChainRegistry/ChainAccountModel.swift
> +// struct ChainAccountModel: Equatable, Hashable, Codable {
comment

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Model/ChainRegistry/MetaAccountModel.swift
> +    var utilsModel: SSFModels.MetaAccountModel {
Let's think about protocol for SSFModels.MetaAccountModel

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Model/Currency.swift
> +// struct Currency: Codable, Equatable, Hashable {
comment

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Services/ChainRegistry/ChainSyncService.swift
> +    static let fetchLocalData = true
discard please and update dev chains.json

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeProvider.swift
> +// <<<<<<< HEAD
best way for resolve conflict

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeSnapshot.swift
> +// struct RuntimeSnapshot {
comment

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeSpecVersion.swift
> +// enum RuntimeSpecVersion: UInt32, CaseIterable {
comment

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Services/RuntimeRegistryService/RuntimeCoderFactory.swift
> +// protocol RuntimeCoderFactoryProtocol {
comment

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Services/RuntimeRegistryService/RuntimeRegistryServiceProtocol.swift
> +// typealias RuntimeMetadataClosure = () throws -> RuntimeMetadata
comment

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Services/ServiceCoordinator.swift
> +    private static func createPackageChainRegistry() -> SSFChainRegistry.ChainRegistryProtocol {
we should use fearless wallet chain registry

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/View/AmountInputView/AmountInputViewV2.swift
> +        view.shadowColor = .clear
Is it possible to turn off the shadow in another way?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/View/ShimmeredProtocol.swift
> +    func startSkeletonAnimation() {}
what should doing this methods?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/Banners/BannersViewModelFactory.swift
> +                let title = "Liquidity pools"
strings

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/Common/LiquidityPools+ViewModel.swift
loooong lines in this file

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/Common/LiquidityPools+ViewModel.swift
> +        let poolReservesValue = (reserves?.reserves.reserves).flatMap { Decimal.fromSubstrateAmount($0, precision: Int16(baseAsset.precision)) }
reserves?.reserves.reserves 🤢

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/LiquidityPoolDetailsAssembly.swift
> +    static func configureModule(assetIdPair: AssetIdPair, chain: ChainModel, wallet: MetaAccountModel, input: LiquidityPoolDetailsInput, poolOperationFlowsClosure: @escaping () -> Void) -> LiquidityP
long line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/LiquidityPoolDetailsInteractor.swift
> +        Task {
please take a look on the AssetManagement module as implemented async style for module. I suggest to discuss async viper module, and further create async template

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/LiquidityPoolDetailsPresenter.swift
> +    case userPool(liquidityPair: LiquidityPair?, reserves: PolkaswapPoolReservesInfo?, apyInfo: PoolApyInfo?, accountPool: AccountPool?, availablePairs: [LiquidityPair]?)
long lines

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/LiquidityPoolDetailsPresenter.swift
> +enum LiquidityPoolDetailsInput {
I suggest transfer to new file

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/LiquidityPoolDetailsPresenter.swift
> +        router.showSupplyFlow(liquidityPair: liquidityPair, chain: chain, wallet: wallet, availablePairs: input.availablePairs, flowClosure: poolOperationFlowsClosure, from: view)
long line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/LiquidityPoolDetailsPresenter.swift
> +        router.showRemoveFlow(liquidityPair: liquidityPair, chain: chain, wallet: wallet, flowClosure: poolOperationFlowsClosure, from: view)
long line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/LiquidityPoolDetailsPresenter.swift
> +        infoText = R.string.localizable.lpApyAlertText(preferredLanguages: selectedLocale.rLanguages)
interesting approach)

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/LiquidityPoolDetailsRouter.swift
> +final class LiquidityPoolDetailsRouter: LiquidityPoolDetailsRouterInput {
long lines, hard to read

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/LiquidityPoolDetailsViewController.swift
> +        rootView.navigationBar.backButton.addAction { [weak self] in
I suggest create method with name like bindActions()

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/LiquidityPoolDetailsViewLayout.swift
> +        bar.backButton.backgroundColor = UIColor(red: 1, green: 1, blue: 1, alpha: 0.08)
what color?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/LiquidityPoolDetailsViewLayout.swift
> +    private func drawSubviews() {
```suggestion
    private func addSubviews() {
```

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/LiquidityPoolDetailsViewLayout.swift
> +        reservesView.titleLabel.text = "TVL"
should be localised?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/Resources/chains.json
make sure what remote json has been updated

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/ViewModel/LiquidityPoolDetailsViewModelFactory.swift
> +        let fiatFormatter = fiatFormatter(for: wallet.selectedCurrency, locale: locale)
what happens if selected currency did eur? We has prices as usd

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolDetails/ViewModel/LiquidityPoolDetailsViewModelFactory.swift
> +            pairTitleLabelText: "\(baseAsset.symbol.uppercased()) › \(targetAsset.symbol.uppercased())",
please remove uppercased from view layer

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityAssembly.swift
> +        guard let secretKeyData = try? fetchSecretKey(
perhaps will better combine two guard state

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityAssembly.swift
> +        let interactor = LiquidityPoolRemoveLiquidityInteractor(lpOperationService: lpOperationService, lpDataService: lpDataService, liquidityPair: liquidityPair, priceLocalSubscriber: PriceLocalSto
long lines

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityAssembly.swift
> +    static func fetchSecretKey(
```suggestion
    private static func fetchSecretKey(
```

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityInteractor.swift
> +        pricesProvider = priceLocalSubscriber.subscribeToPrices(for: chainAssets, listener: self)
looks like we can remove this line?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityPresenter.swift
> +        let baseAssetAmount = baseAssetInputResult?.absoluteValue(from: baseAssetBalance ?? .zero) ?? .zero
this is expected behaviour what will zero?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityPresenter.swift
> +    private func resetLoadingState() {
look like possible combine this method with previous, just pass Bool

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityPresenter.swift
> +        guard let swapFromFee = networkFee, let xorChainAsset = chain.utilityChainAssets().first else {
in remote json can be mistake, perhaps will better use currencyId for looking xor?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityPresenter.swift
> +            for: chain.utilityChainAssets().first
in this place too

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityPresenter.swift
> +        infoText = R.string.localizable.lpApyAlertText(preferredLanguages: selectedLocale.rLanguages)
I've already seen something like that somewhere)

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityPresenter.swift
> +    func selectFromAmountPercentage(_ percentage: Float) {
all methods for update amount what bellow, very similar to each other, I suggest combine common logic in private method

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityPresenter.swift
> +                baseTargetRate = baseAssetPriceValue / targetAssetPriceValue
let's imagine the situation when target price did fetched like zero

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityPresenter.swift
> +            router.present(error: error, from: setupView, locale: selectedLocale)
I guess this error not inform user what happen

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityRouter.swift
> +        guard let module = LiquidityPoolRemoveLiquidityConfirmAssembly.configureModule(wallet: wallet, chain: chain, liquidityPair: liquidityPair, removeInfo: info, flowClosure: flowClosure) else {
long line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityViewController.swift
> +        let isEnabled = amountFromInputViewModel?.isValid == true && amountToInputViewModel?.isValid == true && assetToViewModel != nil && assetFromViewModel != nil
Optional comment.
Code look more readable if use allSatisfy

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidityConfirm/LiquidityPoolRemoveLiquidityConfirmAssembly.swift
> +        let interactor = LiquidityPoolRemoveLiquidityInteractor(lpOperationService: lpOperationService, lpDataService: lpDataService, liquidityPair: liquidityPair, priceLocalSubscriber: PriceLocalSto
long line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidityConfirm/LiquidityPoolRemoveLiquidityConfirmAssembly.swift
> +    static func fetchSecretKey(
```suggestion
    private static func fetchSecretKey(
```

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyAssembly.swift
> +    static func configureModule(chain: ChainModel, wallet: MetaAccountModel, liquidityPair: LiquidityPair, availablePairs: [LiquidityPair]?, flowClosure: @escaping () -> Void) -> LiquidityPoolSupplyM
long line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyAssembly.swift
> +        let interactor = LiquidityPoolSupplyInteractor(lpOperationService: lpOperationService, lpDataService: lpDataService, liquidityPair: liquidityPair, priceLocalSubscriber: PriceLocalStorageSubsc
long line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyAssembly.swift
> +    static func fetchSecretKey(
```suggestion
    private static func fetchSecretKey(
```

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyInteractor.swift
> +        pricesProvider = priceLocalSubscriber.subscribeToPrices(for: chainAssets, listener: self)
looks like we can remove this line?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +    private var slippadgeTolerance: Float = Constants.slippadgeTolerance
```suggestion
    private var slippadgeTolerance: Decimal = Constants.slippadgeTolerance
```

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +        static let slippadgeTolerance: Float = 0.5
```suggestion
        static let slippadgeTolerance: Decimal = 0.5
```

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +        let baseAssetAmount = baseAssetInputResult?.absoluteValue(from: baseAssetBalance ?? .zero) ?? .zero
this is expected behaviour what can bee zero?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +        provideFromAssetVewModel()
should we run in main queue?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +        var infoTitle: String
not changed

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +        var infoTitle: String
not changed

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +    func selectFromAmountPercentage(_ percentage: Float) {
all method for updating amount has common part, let's combine in private method

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +        self.pairs = pairs
should doing something when did received?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +                baseTargetRate = baseAssetPriceValue / targetAssetPriceValue
make sure what targetAssetPriceValue can't be zero

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +            router.present(error: error, from: view, locale: selectedLocale)
this error will not be useful for the user

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +            return
should you doing view.didEndUpdating if will return?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyViewController.swift
> +        let isEnabled = amountFromInputViewModel?.isValid == true && amountToInputViewModel?.isValid == true && assetToViewModel != nil && assetFromViewModel != nil
for more readable code you can use allSatisfy

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyViewController.swift
> +    func didUpdating() {
let's think about name this method

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/ViewModel/LiquidityPoolSupplyViewModelFactory.swift
> +class LiquidityPoolSupplyViewModelFactoryDefault: LiquidityPoolSupplyViewModelFactory {
final

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupplyConfirm/LiquidityPoolSupplyConfirmAssembly.swift
> +    static func fetchSecretKey(
private

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupplyConfirm/LiquidityPoolSupplyConfirmInteractor.swift
> +        pricesProvider = priceLocalSubscriber.subscribeToPrices(for: chainAssets, listener: self)
looks like we can remove this line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupplyConfirm/LiquidityPoolSupplyConfirmPresenter.swift
> +    private func resetLoadingState() {
combine with previous method if possible

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupplyConfirm/LiquidityPoolSupplyConfirmPresenter.swift
> +        var infoTitle: String
not changed

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupplyConfirm/LiquidityPoolSupplyConfirmPresenter.swift
> +        var infoTitle: String
not changed

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupplyConfirm/LiquidityPoolSupplyConfirmPresenter.swift
> +            router.present(error: error, from: view, locale: selectedLocale)
nor useful error for user

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupplyConfirm/LiquidityPoolSupplyConfirmViewLayout.swift
> +//        apyView.addSubview(apyInfoButton)
comments

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolSupplyConfirm/ViewModel/LiquidityPoolSupplyConfirmViewModelFactory.swift
> +        let amountsText = buildAmountsText(baseAssetAmount: baseAssetAmount, targetAssetAmount: targetAssetAmount, baseChainAsset: baseChainAsset, targetChainAsset: targetChainAsset, locale: locale)
long line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/Flows/AvailablePools/AvailableLiquidityPoolsListViewModelFactory.swift
> +        LiquidityPoolListCellModel(tokenPairIconsVieWModel: TokenPairsIconViewModel(firstTokenIconViewModel: nil, secondTokenIconViewModel: nil), tokenPairNameLabelText: nil, rewardTokenNameLabelText
long line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/Flows/AvailablePools/AvailableLiquidityPoolsListViewModelFactory.swift
> +            titleLabelText: "Available pools",
should be localise?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/Flows/AvailablePools/AvailableLiquidityPoolsListViewModelFactory.swift
> +        }.sorted(by: { $0.sortValue > $1.sortValue }).filter {
make methods for new line please

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/Flows/AvailablePools/AvailableLiquidityPoolsListViewModelFactory.swift
> +            titleLabelText: "Available pools",
should be localise

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/Flows/UserPools/UserLiquidityPoolsListPresenter.swift
> +    func didAppearView() {}
empty

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/Flows/UserPools/UserLiquidityPoolsListViewModelFactory.swift
> +        }.sorted(by: { $0.sortValue > $1.sortValue }).filter {
methods for new line please.
If possible I suggest for first doing filter for search text and then build viewModels. Also please check this opportunity in others viewModelFactories

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/LiquidityPoolsListAssembly.swift
> +    static func configureAvailablePoolsModule(chain: ChainModel, wallet: MetaAccountModel, moduleOutput: LiquidityPoolsListModuleOutput?, type: LiquidityPoolListType) -> LiquidityPoolsListModuleCreat
long line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/LiquidityPoolsListAssembly.swift
> +    static func configureUserPoolsModule(chain: ChainModel, wallet: MetaAccountModel, moduleOutput: LiquidityPoolsListModuleOutput?, type: LiquidityPoolListType) -> LiquidityPoolsListModuleCreationRe
long line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/LiquidityPoolsListRouter.swift
> +    func showPoolDetails(assetIdPair: AssetIdPair, chain: ChainModel, wallet: MetaAccountModel, input: LiquidityPoolDetailsInput, poolOperationFlowsClosure: @escaping () -> Void, from view: Controlle
long line

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/LiquidityPoolsListViewController.swift
> +        rootView.tableView.delegate = self
I propose create separate methods for setup table view and bind actions

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/LiquidityPoolsListViewLayout.swift
> +            make.centerY.equalToSuperview()
лишняя линия

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/View/LiquidityPoolListCell.swift
> +    private func drawSubviews() {
```suggestion
    private func addSubviews() {
```

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/View/LiquidityPoolListCell.swift
> +class LiquidityPoolListCell: UITableViewCell {
should be final?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsOverview/LiquidityPoolsOverviewViewLayout.swift
> +//        scrollView.addSubview(containerStackView)
comments

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsOverview/LiquidityPoolsOverviewViewLayout.swift
> +    private func drawSubviews() {
```suggestion
    private func addSubviews() {
```

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/LiquidityPools/LiquidityPoolsOverview/LiquidityPoolsOverviewViewLayout.swift
> +//        containerStackView.snp.makeConstraints { make in
comments

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/MainTabBar/MainTabBarWireframe.swift
> +//            let tabBarController = view?.controller,
comments

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/NewWallet/ChainAssetList/ChainAssetListPresenter.swift
> +    func didTapCloseBanners() {}
to do something here?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/PolkaswapFlow/PolkaswapAdjustment/PolkaswapAdjustmentViewLayout.swift
> +        bannersViewContainer.isHidden = true
can we just do removeFromSuperView() ?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/PolkaswapFlow/PolkaswapAdjustment/PolkaswapAdjustmentViewLayout.swift
> +        addSubview(bannersViewContainer)
please check on the iPhone SE

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/Staking/Services/EraValidatorsService/EraValidatorService+Fetch.swift
> +private typealias IdentifiableExposure = (Data, ValidatorExposure)
where used?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/Wallet/Commands/WalletSelectAccountCommand.swift
who is it?

2024-07-03 08:30 UTC, DRadmir commented on fearless/Modules/Wallet/Commands/WalletSelectAccountCommandFactory.swift
who is it?

2024-07-03 08:30 UTC, DRadmir commented on fearlessTests/Modules/LiquidityPoolDetails/LiquidityPoolDetailsTests.swift
remove or Implement

2024-07-03 08:30 UTC, DRadmir commented on fearlessTests/Modules/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityTests.swift
remove or Implement

2024-07-03 08:30 UTC, DRadmir commented on fearlessTests/Modules/LiquidityPoolRemoveLiquidityConfirm/LiquidityPoolRemoveLiquidityConfirmTests.swift
remove or Implement

2024-07-03 08:30 UTC, DRadmir commented on fearlessTests/Modules/LiquidityPoolSupply/LiquidityPoolSupplyTests.swift
remove or Implement

2024-07-03 08:30 UTC, DRadmir commented on fearlessTests/Modules/LiquidityPoolSupplyConfirm/LiquidityPoolSupplyConfirmTests.swift
remove or Implement

2024-07-03 08:30 UTC, DRadmir commented on fearlessTests/Modules/LiquidityPoolsList/LiquidityPoolsListTests.swift
remove or Implement

2024-07-03 08:30 UTC, DRadmir commented on fearlessTests/Modules/LiquidityPoolsOverview/LiquidityPoolsOverviewTests.swift
remove or Implement

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Storage/SubstrateDataModel.xcdatamodeld/SubstrateDataModel_v5.xcdatamodel/contents
please make sure what you change right xcdatamodel

2024-07-03 08:30 UTC, DRadmir commented on fearless/Common/Storage/SubstrateDataModel.xcdatamodeld/SubstrateDataModel_v7.xcdatamodel/contents
please make sure what you change right xcdatamodel

2024-07-03 08:30 UTC, DRadmir commented on fearless/ApplicationLayer/Services/QRService/QRExtractionServiceError.swift
please check this file, perhaps should be removed? Cause FW moved to package qr service

2024-07-09 07:23 UTC, bnsports commented on fearless/Modules/LiquidityPools/LiquidityPoolRemoveLiquidity/LiquidityPoolRemoveLiquidityPresenter.swift
> +        let baseAssetAmount = baseAssetInputResult?.absoluteValue(from: baseAssetBalance ?? .zero) ?? .zero
yes, we need to estimate fee with some value

2024-07-09 07:37 UTC, bnsports commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +        let baseAssetAmount = baseAssetInputResult?.absoluteValue(from: baseAssetBalance ?? .zero) ?? .zero
yes

2024-07-09 07:38 UTC, bnsports commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +        provideFromAssetVewModel()
jumping to main queue located inside those methods

2024-07-09 07:46 UTC, bnsports commented on fearless/Modules/LiquidityPools/LiquidityPoolSupply/LiquidityPoolSupplyPresenter.swift
> +        self.pairs = pairs
nope, it's optional thing that makes next screen loading faster

2024-07-09 08:11 UTC, bnsports commented on fearless/Modules/LiquidityPools/LiquidityPoolsList/Flows/UserPools/UserLiquidityPoolsListPresenter.swift
> +    func didAppearView() {}
protocol method

2024-07-09 08:18 UTC, bnsports commented on fearless/Modules/NewWallet/ChainAssetList/ChainAssetListPresenter.swift
> +    func didTapCloseBanners() {}
no

2024-08-01 08:25 UTC, DRadmir approved these changes

2024-08-02 05:09 UTC, merged