Feature/nomis integration
soramitsu/fearless-iOS pull request #1276
Opened 2024-07-24 09:04 UTC by bnsports

2024-08-02 08:15 UTC, bnsports commented on fearless/ApplicationLayer/Services/ScamService/ScamInfoFetcher.swift
> +                subtype: "Proceed with caution"
localization

2024-08-02 08:15 UTC, bnsports commented on fearless/ApplicationLayer/Services/SoraFiatService/SubqueryFiatInfoOperation.swift
> +public final class SubqueryFiatInfoOperation<ResultType>: BaseOperation<ResultType> {
possible unused

2024-08-02 08:15 UTC, bnsports commented on fearless/ApplicationLayer/Services/SoraFiatService/SoraFiatService.swift
> +protocol FiatServiceObserverProtocol: AnyObject {
possible unused

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/DataProvider/ExistentialDeposit.swift
> +        case .equilibrium:
remove equilibrium case

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/DataProvider/Sources/PriceDataSource.swift
> +        return []
remove this. chainlink prices were disabled on config

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Extension/Foundation/NumberFormatter.swift
> +    static var nomisHours: NumberFormatter {
unused

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Model/AssetVisibility.swift
> +// struct AssetVisibility: Codable, Equatable, Hashable, Identifiable {
commented code

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Model/ChainRegistry/ChainAccountModel.swift
> +// struct ChainAccountModel: Equatable, Hashable, Codable {
commented code

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Model/ChainRegistry/MetaAccountModel.swift
> +        SSFModels.MetaAccountModel(metaId: metaId, name: name, substrateAccountId: substrateAccountId, substrateCryptoType: substrateCryptoType, substratePublicKey: substratePublicKey, ethereumAddres
line wrapping

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Model/Currency.swift
> +// struct Currency: Codable, Equatable, Hashable {
commented code

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Services/ChainRegistry/ChainRegistry.swift
> +    func getChainUnsafe(for chainId: ChainModel.Id) -> ChainModel?
remove this

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Services/ChainRegistry/ChainRegistry.swift
> +        DispatchQueue.global(qos: .background).async { [weak self] in
remove thread management

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Services/ChainRegistry/ChainRegistry.swift
> +//        readLock.concurrentlyRead {
commented code

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeProvider.swift
> +// <<<<<<< HEAD
commented code

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeSnapshot.swift
> +// struct RuntimeSnapshot {
commented code

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeSpecVersion.swift
> +// enum RuntimeSpecVersion: UInt32, CaseIterable {
commented code

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Services/RuntimeRegistryService/RuntimeCoderFactory.swift
> +// protocol RuntimeCoderFactoryProtocol {
commented code

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/Services/RuntimeRegistryService/RuntimeRegistryServiceProtocol.swift
> +// typealias RuntimeMetadataClosure = () throws -> RuntimeMetadata
commented code

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/View/AccountScore/AccountScoreView.swift
> +        let spaceSize = CGSize(width: 32, height: 15)
size to constants

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/View/AccountScore/AccountScoreView.swift
> +        starView.text = "N/A"
localization ?

2024-08-02 08:15 UTC, bnsports commented on fearless/Common/ViewModel/AccountScore/AccountScoreViewModel.swift
> +        if score < 0.25 {
check corectness

2024-08-02 08:15 UTC, bnsports commented on fearless/Modules/Banners/BannersViewModelFactory.swift
> +                let title = "Liquidity pools"
localization

2024-08-02 08:15 UTC, bnsports commented on fearless/Modules/Send/SendDependencyContainer.swift
> +//        cachedDependencies[chainAsset.uniqueKey(accountId: accountResponse.accountId)] = dependencies
commented code

2024-08-02 09:32 UTC, DRadmir requested changes

2024-08-02 09:32 UTC, DRadmir commented on fearless.xcworkspace/xcshareddata/swiftpm/Package.resolved
> +        "branch" : "network-module-update",
should be merged in fearless wallet branch

2024-08-02 09:32 UTC, DRadmir commented on fearless/ApplicationLayer/Services/AccountStatistics/Nomis/NomisAccountStatisticsFetcher.swift
> +        guard let baseURL = URL(string: "https://api.nomis.cc/api/v1/multichain-score/wallet/") else {
Better use remote or ApplicationConfig

2024-08-02 09:32 UTC, DRadmir commented on fearless/ApplicationLayer/Services/AccountStatistics/Nomis/NomisAccountStatisticsFetcher.swift
> +        guard let baseURL = URL(string: "https://api.nomis.cc/api/v1/multichain-score/wallet/") else {
Better use remote or ApplicationConfig

2024-08-02 09:32 UTC, DRadmir commented on fearless/ApplicationLayer/Services/ScamService/ScamInfoFetcher.swift
> +                type: .lowScore,
why hard code?

2024-08-02 09:32 UTC, DRadmir commented on fearless/ApplicationLayer/Services/ScamService/ScamInfoFetcher.swift
> +        try await withCheckedThrowingContinuation { continuation in
I propose use async repository

2024-08-02 09:32 UTC, DRadmir commented on fearless/Common/Extension/ChainModel+Nomis.swift
> +        chainId == "137" || chainId == "1" || chainId == "56"
Just append isNomisSupported in chain options

2024-08-02 09:32 UTC, DRadmir commented on fearless/Common/Model/AccountStatistics.swift
> +        nativeBalanceUSD = try? container.decodeIfPresent(Decimal.self, forKey: .nativeBalanceUSD)
the you use optional try?

2024-08-02 09:32 UTC, DRadmir commented on fearless/Common/Model/ScamInfo.swift
> +        case lowScore = "Low network activity"
can we remove raw value?

2024-08-02 09:32 UTC, DRadmir commented on fearless/Common/Services/ChainRegistry/ChainRegistry.swift
> +        _ = try? ethereumConnectionPool.setupConnection(for: newChain)
use do catch and logger

2024-08-02 09:32 UTC, DRadmir commented on fearless/Common/Services/ChainRegistry/ChainRegistry.swift
> +        _ = try? ethereumConnectionPool.setupConnection(for: updatedChain)
use do catch and logger

2024-08-02 09:32 UTC, DRadmir commented on fearless/Common/ViewModel/AccountScore/AccountScoreViewModel.swift
> +                print("Account statistics fetching error: ", error)
replace print to logger

2024-08-02 09:32 UTC, DRadmir commented on fearless/Modules/AccountStatistics/AccountStatisticsPresenter.swift
> +    func didReceiveAccountStatisticsError(_: Error) {}
unused

2024-08-02 09:32 UTC, DRadmir commented on fearlessTests/Modules/AccountStatistics/AccountStatisticsTests.swift
> +class AccountStatisticsTests: XCTestCase {
remove

2024-08-02 10:07 UTC, bnsports commented on fearless/Common/Model/ScamInfo.swift
> +        case lowScore = "Low network activity"
no

2024-08-06 05:31 UTC, DRadmir approved these changes

2024-08-06 07:50 UTC, merged