Price update center
soramitsu/fearless-iOS pull request #1280
Opened 2024-08-12 06:05 UTC by Viscount88

2024-08-12 09:44 UTC, bnsports commented on fearless/Common/Services/PricesService.swift
> +    func handlePrices(result: Result<[PriceData], Error>) {
is it possible to change this delegate method by changing [PriceData] to [ChainAsset: PriceData] ?

2024-08-30 07:58 UTC, DRadmir requested changes

2024-08-30 07:58 UTC, DRadmir commented on fearless/Common/DataProvider/Subscription/PriceLocalSubscriptionHandler.swift
Needs to review this protocol. And if possible remove unused method and extension with default implementation. 
How I understand you use one method from this protocol.

2024-08-30 07:58 UTC, DRadmir commented on fearless/Common/Helpers/AssetModelMapper.swift
> +    private func createPriceData(from entity: CDPriceData) -> PriceData? {
Move private method to the class body

2024-08-30 07:58 UTC, DRadmir commented on fearless/Common/Services/ChainRegistry/RuntimeProviderPool/SnapshotHotBootBuilder.swift
> +                saveOperation.completionBlock = { [weak self] in
This code should be removed

2024-08-30 07:58 UTC, DRadmir commented on fearless/Common/Services/PricesService.swift
> +            switch saveOperation.result {
This block should be removed

2024-08-30 07:58 UTC, DRadmir commented on fearless/Common/Services/PricesService.swift
> +        let saveOperation = chainRepository.saveOperation({
I don't see any changes in our ChainRegistry. Please note that, in chain registry we subscribed on the chainRepository via provider. ChainRegistry always adds the chain on the property, which can occupy the memory

2024-08-30 07:58 UTC, DRadmir commented on fearless/Modules/AssetManagement/ViewModel/AssetManagementViewModelFactory.swift
> +            priceData: cell.chainAsset.asset.getPrice(for: wallet.selectedCurrency),
It would be better if we get the price once for all operations below

2024-08-30 07:58 UTC, DRadmir commented on fearless/Modules/AssetManagement/ViewModel/AssetManagementViewModelFactory.swift
> +                priceData: chainAsset.asset.getPrice(for: wallet.selectedCurrency),
It would be better if we get the price once for all operations below

2024-08-30 07:58 UTC, DRadmir commented on fearless/Modules/BalanceLocksDetail/BalanceLocksDetailPresenter.swift
> +    private let wallet: MetaAccountModel
I propose passing only selectedCurrency instead of wallet

2024-08-30 07:58 UTC, DRadmir commented on fearless/Modules/Crowdloan/CrowdloanContributionConfirm/CrowdloanContributionConfirmPresenter.swift
> +    let wallet: MetaAccountModel
I propose passing only selectedCurrency instead of wallet

2024-08-30 07:58 UTC, DRadmir commented on fearless/Modules/Crowdloan/CrowdloanContributionSetup/CrowdloanContributionSetupPresenter.swift
> +    let wallet: MetaAccountModel
I propose passing only selectedCurrency instead of wallet

2024-08-30 07:58 UTC, DRadmir commented on fearless/Modules/NewWallet/ChainAssetList/ViewModel/ChainAssetListViewModelFactory.swift
> +                isUpdated: true
Should we still use ShimmeredLabelState?

2024-08-30 07:58 UTC, DRadmir commented on fearless/Modules/NewWallet/ChainAssetList/ViewModel/ChainAssetListViewModelFactory.swift
> +                isUpdated: true
Should we still use ShimmeredLabelState?

2024-08-30 07:58 UTC, DRadmir commented on fearless/Modules/NewWallet/ChainAssetList/ViewModel/ChainAssetListViewModelFactory.swift
> +                isUpdated: true
Should we still use ShimmeredLabelState?

2024-08-30 07:58 UTC, DRadmir commented on fearless/Modules/NewWallet/ChainAssetList/ViewModel/ChainAssetListViewModelFactory.swift
> +            priceDataWasUpdated: true,
I suggest removing this logic

2024-09-02 04:46 UTC, Viscount88 commented on fearless/Common/Services/PricesService.swift
> +        let saveOperation = chainRepository.saveOperation({
check pls

2024-09-02 05:29 UTC, bnsports submitted a review, later dismissed

2024-09-02 05:29 UTC, bnsports commented on fearless/Common/Services/PricesService.swift
> +        assets = chainAssets.map { $0.asset }.uniq(predicate: { assetModel in
why?

2024-10-09 11:06 UTC, DRadmir approved these changes

2024-10-09 11:06 UTC, merged