Tests/(flw 1802) switch unit tests to multiasset
soramitsu/fearless-iOS pull request #668
Opened 2022-05-30 06:36 UTC by Viscount88

2022-06-01 03:16 UTC, DRadmir commented on fearlessTests/Common/Services/ExtrinsicProcessingTests.swift
> +            let eventRecords: [EventRecord] = try decoder.read(of: "")
decoder.read(of: "") will not throw the error?

2022-06-06 07:51 UTC, posplaw requested changes

2022-06-06 07:51 UTC, posplaw commented on fearless/Common/Helpers/DerivationPathConstants.swift
> +    static let testEthereum = "//12//34//5/6/7"
I would test empty derivation path also, and please add TODO for when we add no fixed length deviation path support

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Common/Crypto/SigningWrapperTests.swift
> +        try AccountCreationHelper.createMetaAccountFromSeed(substrateSeed: Self.substrateSeed,
Please keep our default padding and lines rule: move to the next line

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Common/Crypto/SigningWrapperTests.swift
> +        try AccountCreationHelper.createMetaAccountFromKeystore(substrateFilename: Constants.validSrKeystoreName,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Common/Crypto/SigningWrapperTests.swift
> +        try AccountCreationHelper.createMetaAccountFromSeed(substrateSeed: Self.substrateSeed,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Common/Crypto/SigningWrapperTests.swift
> +        try AccountCreationHelper.createMetaAccountFromKeystore(substrateFilename: Constants.validEd25519KeystoreName,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Common/Crypto/SigningWrapperTests.swift
> +        try AccountCreationHelper.createMetaAccountFromSeed(substrateSeed: Self.substrateSeed,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Common/Crypto/SigningWrapperTests.swift
> +        try AccountCreationHelper.createMetaAccountFromKeystore(substrateFilename: Constants.validEcdsaKeystoreName,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Common/Storage/AccountItemMapperTests.swift
> +        let metaAccountItem = MetaAccountModel(metaId: UUID().uuidString,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Helper/AccountCreationHelper.swift
> +        let request = MetaAccountImportMnemonicRequest(mnemonic: mnemonic,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Helper/AccountCreationHelper.swift
> +        ethereumSeed: String?,
Why optional?

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Helper/AccountCreationHelper.swift
> +        let request = MetaAccountImportSeedRequest(substrateSeed: substrateSeed,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Helper/AccountCreationHelper.swift
> +        return try createMetaAccountFromKeystoreData(substrateData: substrateData,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Helper/AccountCreationHelper.swift
> +        let request = MetaAccountImportKeystoreRequest(substrateKeystore: substrateKeystoreString,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Helper/AccountGenerator.swift
> +        return MetaAccountModel(metaId: UUID().uuidString,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Helper/ChainModelGenerator.swift
> +                            chainId: chainId,
Please fix paddings here, as well as closing bracket

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Helper/ChainModelGenerator.swift
> +            let chainAssets = Set(arrayLiteral: chainAsset)
Why not assign to `chain.assets` immediately? What this variable for?

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Helper/ChainModelGenerator.swift
> +        ChainAssetModel(assetId: asset.id,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Mocks/DataProviders/ExtrinsicOperationFactoryStub.swift
> +        return BaseOperation()
Redundant return

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Mocks/DataProviders/RuntimeCodingServiceStub.swift
> +        return nil
Redundant return

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/AccountConfirm/AccountConfirmTests.swift
> +        let newAccountRequest = MetaAccountImportMnemonicRequest(mnemonic: mnemonic,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/AccountConfirm/AccountConfirmTests.swift
> +        let presenter = AccountConfirmPresenter(interactor: interactor,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/AccountCreate/AccountCreateTests.swift
> +        let presenter = AccountCreatePresenter(usernameSetup: usernameSetup,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/AccountImport/AccountImportTests.swift
> +        let presenter = AccountImportPresenter(wireframe: wireframe,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/AccountManagement/AccountManagementTests.swift
> +        let presenter = AccountManagementPresenter(viewModelFactory: viewModelFactory,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/AssetSelection/AssetSelectionTests.swift
> +    func subscribe(chain: ChainModel,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/AssetSelection/AssetSelectionTests.swift
> +        let interactor = ChainSelectionInteractor(selectedMetaAccount: selectedAccount,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ChainAccountBalanceList/ChainAccountBalanceListTests.swift
> +        var assets: [AssetModel] = []
Why not `let assets = chains.reduce([]) { $0 + $1.assets }.map { $0.asset }` ? Instead of for/for accumulation

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ChainAccountBalanceList/ChainAccountBalanceListTests.swift
> +        let presenter = ChainAccountBalanceListPresenter(interactor: interactor,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ChainAccountBalanceList/ChainAccountBalanceListTests.swift
> +        let adapter = AccountInfoSubscriptionAdapter(walletLocalSubscriptionFactory: walletLocalSubscriptionFactory,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ChainAccountBalanceList/ChainAccountBalanceListTests.swift
> +        return ChainAccountBalanceListInteractor(selectedMetaAccount: selectedAccount,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ChainSelection/ChainSelectionTests.swift
> +        let adapter = AccountInfoSubscriptionAdapter(walletLocalSubscriptionFactory: walletLocalSubscriptionFactory,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ControllerAccount/ControllerAccountTests.swift
> +        let chain = ChainModelGenerator.generateChain(generatingAssets: 1,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ControllerAccount/ControllerAccountTests.swift
> +        let presenter = ControllerAccountPresenter(wireframe: wireframe,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ControllerAccount/ControllerAccountTests.swift
> +        let chainAccountItem = ChainAccountResponse(chainId: chain.chainId,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ExportMnemonic/ExportMnemonicTests.swift
> +        try AccountCreationHelper.createMetaAccountFromMnemonic(cryptoType: .sr25519,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ExportMnemonic/ExportMnemonicTests.swift
> +        let chain = ChainModelGenerator.generateChain(generatingAssets: 1,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ExportMnemonic/ExportMnemonicTests.swift
> +        let presenter = ExportMnemonicPresenter(flow: .single(chain: chain,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ExportMnemonic/ExportMnemonicTests.swift
> +        let importRequest = MetaAccountImportMnemonicRequest(mnemonic: mnemonic,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ExportMnemonic/ExportMnemonicTests.swift
> +        try AccountCreationHelper.createMetaAccountFromMnemonic(cryptoType: .sr25519,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ExportMnemonic/ExportMnemonicTests.swift
> +        let chain = ChainModelGenerator.generateChain(generatingAssets: 1,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/ExportMnemonic/ExportMnemonicTests.swift
> +        let importRequest = MetaAccountImportMnemonicRequest(mnemonic: mnemonic,
Padding/lines

2022-06-06 07:51 UTC, posplaw commented on fearlessTests/Modules/Root/RootTests.swift
> +        let startViewHelper = StartViewHelper(keystore: keystore,
Padding/lines

2022-07-25 09:24 UTC, DRadmir approved these changes

2022-07-27 04:42 UTC, closed without merging