staking analytics for moonbeam
soramitsu/fearless-iOS pull request #714
Opened 2022-07-26 10:58 UTC by bnsports

2022-07-26 11:23 UTC, bnsports commented on fearless/Common/DataProvider/Sources/Rewards/SubqueryRewardsSource.swift
> +        return """
add timestamp filter

2022-07-26 11:23 UTC, bnsports commented on fearless/Common/Network/Subquery/SubqueryRewardOperationFactory.swift
> +                    delegators(
timestamp filter

2022-07-26 11:23 UTC, bnsports commented on fearless/Modules/Staking/Analytics/Validators/AnalyticsValidatorsPresenter.swift
> +        // TODO: Parachain case if needed
remove todo

2022-07-26 11:23 UTC, bnsports commented on fearless/Modules/Staking/StakingMain/StakingMainInteractor+InputProtocol.swift
> +            if chainAsset.stakingType == .paraChain,
not beautiful

2022-07-26 11:23 UTC, bnsports commented on fearless/Modules/Staking/StakingMain/StakingMainInteractor+Subscription.swift
> +                period: .month
week

2022-07-26 11:23 UTC, bnsports commented on fearless/Modules/Staking/StakingMain/StakingMainInteractor+Subscription.swift
> +        presenter?.didReceieve(subqueryRewards: result, period: .month)
week

2022-07-26 11:23 UTC, bnsports commented on fearless/Modules/Staking/StakingMain/StakingMainViewFactory.swift
> +        let stakingAnalyticsLocalSubscriptionFactory = ParachainAnalyticsLocalSubscriptionFactory(
add condition to decide what factory we should use

2022-07-26 11:23 UTC, bnsports commented on fearless/Modules/Staking/StakingMain/View/RewardAnalyticsWidgetView.swift
> +//            startLoading()
check this

2022-07-26 12:26 UTC, DRadmir requested changes

2022-07-26 12:26 UTC, DRadmir commented on fearless/Common/Network/Subquery/SubqueryRewardOperationFactory.swift
> +        address: String,
use one code style for this file please. You used in 121 line "_ address", but here "address"

2022-07-26 12:26 UTC, DRadmir commented on fearless/Modules/Staking/Analytics/Rewards/Flow/Parachain/AnalyticRewardsParachainViewModelFactory.swift
> +        let yValue = rewardsByDate.1
The name of the variable is a little misleading, in fact there "yValues"

2022-07-26 12:26 UTC, DRadmir commented on fearless/Modules/Staking/StakingMain/StakingMainInteractor+Subscription.swift
> +//            subscribeRewardsAnalytics(for: stashItem.stash)
check this comment plz

2022-07-26 12:26 UTC, DRadmir commented on fearless/Modules/Staking/StakingMain/StakingMainViewController.xib
> -    <designables>
this is okey?

2022-07-27 03:52 UTC, DRadmir approved these changes

2022-07-27 04:23 UTC, merged