Feature/flw 2226 wallet main container module proccess
soramitsu/fearless-iOS pull request #740
Opened 2022-08-11 05:24 UTC by DRadmir

2022-08-11 07:24 UTC, Viscount88 requested changes

2022-08-11 07:24 UTC, Viscount88 commented on fearless/Modules/MainNftContainer/MainNftContainerViewLayout.swift
> +        label.text = "NFTs are going to be here soon"
Should be localized

2022-08-11 07:24 UTC, Viscount88 commented on fearless/Modules/NewWallet/ChainAccountBalanceList/Views/ChainAccountBalanceTableCell.swift
> +        let chainIcons = viewModel.assetContainsChainAssets.map {
if viewModel.assetContainsChainAssets.count > 1 { map() } else { [] }

2022-08-11 07:24 UTC, Viscount88 commented on fearless/Modules/WalletMainContainer/WalletMainContainerPresenter.swift
> +//        router.showSearch(from: view)
uncomment

2022-08-11 07:24 UTC, Viscount88 commented on fearless/Modules/WalletMainContainer/WalletMainContainerViewController.swift
> +        balanceInfoViewController: UIViewController,
mb we can receive pageControllers array on init, because it never change.

2022-08-11 07:24 UTC, Viscount88 commented on fearless/Modules/WalletMainContainer/WalletMainContainerViewLayout.swift
> +//        view.stackView.isLayoutMarginsRelativeArrangement = true
remove

2022-08-11 07:24 UTC, Viscount88 commented on fearless/Modules/WalletMainContainer/WalletMainContainerViewLayout.swift
> +//        contentView.stackView.setCustomSpacing(16, after: segmentedControl)
remove

2022-08-11 07:24 UTC, Viscount88 commented on fearless/Modules/WalletMainContainer/WalletMainContainerViewLayout.swift
> +    let backgroundImageView: UIImageView = {
all views private

2022-08-11 07:34 UTC, DRadmir commented on fearless/Modules/BalanceInfo/BalanceInfoViewModelFactory.swift
> +        var dayChangeValue: String = balanceTokenFormatterValue.stringFromDecimal(abs(dayChangeValue)) ?? ""
if dayChangeValue is negative balanceTokenFormatterValue returned nil. And in design positive and negative have red and green color

2022-08-11 07:34 UTC, DRadmir commented on fearless/Modules/ChainAssetList/ChainAssetListInteractor.swift
> +    let priceLocalSubscriptionFactory: PriceProviderFactoryProtocol
is not private, protocol variables

2022-08-16 05:56 UTC, Viscount88 approved these changes

2022-08-16 05:56 UTC, merged