(flw 2420) address book module
soramitsu/fearless-iOS pull request #781
Opened 2022-10-11 09:12 UTC by Viscount88

2022-10-11 13:34 UTC, bnsports requested changes

2022-10-11 13:34 UTC, bnsports commented on fearless/Modules/Contacts/View Models/AddressBookViewModelFactory.swift
> +                contact.name.first == firstLetter
case-sensetive compare

2022-10-11 13:34 UTC, bnsports commented on fearless/Modules/CreateContact/CreateContactViewLayout.swift
> +        view.stackView.layoutMargins = UIEdgeInsets(top: 24.0, left: 0.0, bottom: 0.0, right: 0.0)
please check that you really need 24px top inset

2022-10-11 15:17 UTC, Viscount88 commented on fearless/Modules/Contacts/ContactsViewController.swift
> +        output.didSelect(address: sections[indexPath.section].cells[indexPath.row].contactType.address)
where are cell model actually

2022-10-13 08:27 UTC, bnsports approved these changes

2022-10-13 08:42 UTC, merged