FLW-2454 buttons layout fix
soramitsu/fearless-iOS pull request #788
Opened 2022-10-14 10:54 UTC by bnsports

2022-10-14 10:54 UTC, Viscount88 approved these changes

2022-10-24 04:10 UTC, DRadmir requested changes

2022-10-24 04:10 UTC, DRadmir commented on fearless.xcodeproj/project.pbxproj
> +				MARKETING_VERSION = 2.0.15;
why?

2022-10-24 06:52 UTC, DRadmir approved these changes

2022-10-24 10:49 UTC, merged