Fix/flw 1905 random crash
soramitsu/fearless-iOS pull request #817
Opened 2022-11-08 04:35 UTC by DRadmir

2022-11-08 04:45 UTC, Viscount88 approved these changes

2022-11-08 04:55 UTC, Viscount88 requested changes

2022-11-08 04:55 UTC, Viscount88 commented on fearless/Common/Services/ChainRegistry/ConnectionPool/ConnectionPool.swift
> +    case onlyOneNode
noAvailableNodes sounds better

2022-11-11 05:50 UTC, bnsports requested changes

2022-11-11 05:50 UTC, bnsports commented on fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeSnapshotOperationFactory.swift
> +        _: StorageHasher,
not used

2022-11-11 05:50 UTC, bnsports commented on fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeHotBootSnapshotFactory.swift
> +        _: StorageHasher,
unused

2022-11-11 06:56 UTC, bnsports approved these changes

2022-11-11 06:57 UTC, Viscount88 approved these changes

2022-11-11 06:57 UTC, merged