(flw 2464) send flow update
soramitsu/fearless-iOS pull request #819
Opened 2022-11-08 06:10 UTC by Viscount88

2022-11-09 03:42 UTC, DRadmir requested changes

2022-11-09 03:42 UTC, DRadmir commented on fearless/Modules/Send/SendProtocols.swift
> +    func close(view: ControllerBackedProtocol?)
we have dismissible protocol

2022-11-09 03:42 UTC, DRadmir commented on fearless/Modules/Send/SendViewController.swift
> +        rootView.navigationBar.backButton.addTarget(self, action: #selector(backButtonClicked), for: .touchUpInside)
long lines

2022-11-09 03:42 UTC, DRadmir commented on fearlessTests/Modules/SelectAsset/SelectAssetTests.swift
> +class SelectAssetTests: XCTestCase {
remove

2022-11-09 03:42 UTC, DRadmir commented on fearlessTests/Modules/Send/SendTests.swift
> +class SendTests: XCTestCase {
remove

2022-11-10 06:55 UTC, Viscount88 commented on fearless/Modules/Send/SendInteractor.swift
> +    let dependencyContainer: SendDepencyContainer
because presenter use it. We need balanceViewModelFactory for selected chain asset and I don't want to duplicate this container inside presenter.

2022-11-11 04:22 UTC, DRadmir approved these changes

2022-11-11 04:22 UTC, DRadmir commented on fearless/Modules/SelectAsset/View/SelectAssetCell.swift
> +    private func updateSelectionState() {}
empty method

2022-11-11 06:32 UTC, merged