Release/2.1.0 fix
soramitsu/fearless-iOS pull request #831
Opened 2022-11-16 09:47 UTC by DRadmir

2022-11-16 10:05 UTC, DRadmir reviewed
Self control

2022-11-16 10:05 UTC, DRadmir commented on fearless/Modules/NewWallet/ChainAssetList/ChainAssetListViewLayout.swift
> +    private let container = UIView()
contentContainer

2022-11-16 10:05 UTC, DRadmir commented on fearless/Modules/Send/SendPresenter.swift
> +    private var balanceMinusFeeAndTip: Decimal { (balance ?? 0) - (fee ?? 0) - (tip ?? 0) }
Please approve this logic @bnsports

2022-11-17 04:14 UTC, bnsports requested changes

2022-11-17 04:22 UTC, bnsports approved these changes

2022-11-17 04:22 UTC, merged