FLW-2929: Eq balance logic
soramitsu/fearless-iOS pull request #883
Opened 2023-01-25 08:49 UTC by DRadmir

2023-01-26 02:54 UTC, bnsports requested changes

2023-01-26 02:54 UTC, bnsports commented on fearless/ApplicationLayer/Services/Equilibrium/EquilibriumTotalWalletService.swift
> +    private let equiliriubChainAsset: ChainAsset
typo: equilibrium

2023-01-26 02:54 UTC, bnsports commented on fearless/ApplicationLayer/Services/Equilibrium/EquilibriumTotalWalletService.swift
> +    func fetchTotalBalance(handler: EquilibriumTotalBalanceServiceDelegate) {
let's think about using closure instead of delegate. it's more flexible way

2023-01-26 02:54 UTC, bnsports commented on fearless/Common/Model/ChainAsset.swift
> +            storagePath = StorageCodingPath.account
case .normal, equilibrium:

2023-01-26 02:54 UTC, bnsports commented on fearless/Modules/Send/SendDependencyContainer.swift
> +    func createEqTotalBalanceService() -> EquilibriumTotalBalanceServiceProtocol? {
why not just store this service as part of 'SendDependencies' ?

2023-01-26 05:31 UTC, DRadmir commented
- [ ] Merge brach after release

2023-02-02 07:28 UTC, bnsports approved these changes

2023-02-02 08:03 UTC, merged