Feature/subsquid
soramitsu/fearless-iOS pull request #885
Opened 2023-01-26 04:46 UTC by bnsports

2023-01-27 10:07 UTC, DRadmir requested changes

2023-02-07 08:56 UTC, bnsports commented on fearless/Common/Extension/Wallet/AssetTransactionData+GiantsquidHistory.swift
> +            details: "#\(reward.era ?? 0)",
becuase in UI it should looks like "Round #1234"

2023-02-07 08:56 UTC, bnsports commented on fearless/Common/Extension/Wallet/AssetTransactionData+GiantsquidHistory.swift
> +            details: "#\(bond.blockNumber)",
because in UI it should looks like "Round #1234"

2023-02-07 10:27 UTC, DRadmir requested changes

2023-02-07 10:27 UTC, DRadmir commented on fearless/Common/Network/Giantsquid/GiantsquidTransfer.swift
> +        let date = dateFormatter.value(for: Locale.current).date(from: timestamp)
use localisation manager

2023-02-07 10:27 UTC, DRadmir commented on fearless/CoreLayer/OperationFactory/BlockExplorer/Rewards/SubsquidRewardOperationFactory.swift
> +            let dateFormatter = DateFormatter.suibsquidInputDate.value(for: Locale.current)
locale

2023-02-08 03:34 UTC, DRadmir approved these changes

2023-02-08 03:44 UTC, merged