Fixes/2.2.1/al
soramitsu/fearless-iOS pull request #917
Opened 2023-02-14 07:37 UTC by bnsports

2023-02-17 08:42 UTC, DRadmir requested changes

2023-02-17 08:42 UTC, DRadmir commented on fearless/Common/Model/ChainRegistry/ChainModel.swift
> +        if isPolkadotOrKusama {
use `func explorerUrl(for value: String, type: ChainModel.SubscanType) -> URL?` for return optional URL

2023-02-17 08:42 UTC, DRadmir commented on fearless/CoreLayer/OperationFactory/BlockExplorer/History/Staking/ParachainSubsquidHistoryOperationFactory.swift
> +        let url = self.url
why?

2023-02-20 03:13 UTC, bnsports commented on fearless.xcodeproj/xcshareddata/xcschemes/fearless.xcscheme
> -      region = "PT"
it's hardcoded "Portugal" location in scheme. used to test number formatting.

2023-02-20 03:27 UTC, DRadmir approved these changes

2023-02-20 03:43 UTC, merged