Fix/rd
soramitsu/fearless-iOS pull request #920
Opened 2023-02-14 11:24 UTC by DRadmir

2023-02-17 07:35 UTC, bnsports requested changes

2023-02-17 07:35 UTC, bnsports commented on fearless/Common/View/DetailsTriangularedView.swift
> +    var iconInCenterY: Bool = false {
bad naming. iconShouldCenterVertically

2023-02-17 07:35 UTC, bnsports commented on fearless/Modules/PolkaswapFlow/PolkaswapAdjustment/PolkaswapAdjustmentViewLayout.swift
> +        layoutIfNeeded()
is it still needed?

2023-02-17 07:35 UTC, bnsports commented on fearless/Modules/PolkaswapFlow/PolkaswapAdjustment/PolkaswapAdjustmentViewLayout.swift
> +        disclaimerView.title = "DISCLAIMER"
localization missed for all 3 lines

2023-02-17 07:35 UTC, bnsports commented on fearless/Modules/PolkaswapFlow/PolkaswapDisclaimer/PolkaswapDisclaimerViewController.swift
> +            rootView.continueButton.isEnabled = true
rootView.continueButton.isEnabled = isRead

2023-02-17 07:35 UTC, bnsports commented on fearless/Modules/PolkaswapFlow/PolkaswapDisclaimer/PolkaswapDisclaimerViewLayout.swift
> +            make.bottom.equalTo(bottomContainer.snp.top).offset(-UIConstants.bigOffset)
can't you use 'inset' instead of '-' ?

2023-02-17 07:35 UTC, bnsports commented on fearless/Modules/PolkaswapFlow/PolkaswapDisclaimer/PolkaswapDisclaimerViewModelFactory.swift
> +        attributedString.addAttributes(
what is 'length: 10' ?

2023-02-17 07:35 UTC, bnsports commented on fearless/Modules/PolkaswapFlow/PolkaswapDisclaimer/PolkaswapDisclaimerInteractor.swift
> +    private func fetchDisclaimerRead() {
fetchDisclaimerIsRead

2023-02-17 07:35 UTC, bnsports commented on fearless/Modules/PolkaswapFlow/PolkaswapAdjustment/PolkaswapAdjustmentInteractor.swift
> +        output?.didReceiveDisclaimer(visible: !isVisible)
visible: !isVisible ? you have to decide

2023-02-17 07:35 UTC, bnsports commented on fearless/Common/Helpers/LinkDecorator.swift
> +            let locationAfterRemovingPercents = result.element.range.location - 2 * 2 * result.offset
unclear implementation. what is 2 * 2 ?

2023-02-17 07:35 UTC, bnsports commented on fearless/Common/Helpers/LinkDecorator.swift
> +            let lengthAfterRemovingPercents = result.element.range.length - 4
what is 4 ?

2023-02-17 08:53 UTC, DRadmir commented on fearless/Modules/PolkaswapFlow/PolkaswapDisclaimer/PolkaswapDisclaimerViewModelFactory.swift
> +        attributedString.addAttributes(
This is "IMPORTANT:"

2023-02-20 03:22 UTC, bnsports approved these changes

2023-02-20 03:23 UTC, merged