(flw 2972) UI review fixes
soramitsu/fearless-iOS pull request #933
Opened 2023-03-09 05:55 UTC by Viscount88

2023-03-13 09:26 UTC, bnsports requested changes

2023-03-13 09:26 UTC, bnsports commented on fearless/Common/Model/ChainEcosystem.swift
> +    var isKusama: Bool {
please add isPolkadot case, otherwise you'll need to check !isKusama for case you need polkadot

2023-03-13 09:26 UTC, bnsports commented on fearless/Modules/NewWallet/ChainAccount/ChainAccountInteractor.swift
> -        chainAssetFetching: ChainAssetFetchingProtocol
module should be independence, please leave chainAssetFetching and pass ChainEcosystem to filter fetched chains

2023-03-14 06:50 UTC, bnsports approved these changes

2023-03-14 10:39 UTC, bnsports submitted a review, later dismissed

2023-03-15 04:03 UTC, bnsports approved these changes

2023-03-15 04:19 UTC, Viscount88 commented on fearless/Modules/NewWallet/ChainAssetList/ChainAssetListPresenter.swift
> +                chainAssets: viewModel.assetContainsChainAssets
Remove chainAssets

2023-03-15 04:19 UTC, Viscount88 commented on fearless/Modules/NewWallet/ChainAssetList/ChainAssetListProtocols.swift
> +        chainAssets: [ChainAsset]
remove

2023-03-15 04:19 UTC, Viscount88 commented on fearless/Modules/NewWallet/ChainAssetList/ChainAssetListRouter.swift
> +        chainAssets: [ChainAsset]
Remove

2023-03-15 04:19 UTC, Viscount88 commented on fearless/Modules/NewWallet/ChainAssetList/ViewModel/ChainAssetListViewModelFactory.swift
> +                chainAssets: assetChainAssets.chainAssets,
Mb here too

2023-03-15 04:19 UTC, Viscount88 commented on fearless/Modules/NewWallet/WalletChainAccountDashboard/WalletChainAccountDashboardViewFactory.swift
> +        chainAssets _: [ChainAsset]
Not used

2023-03-15 05:12 UTC, bnsports approved these changes

2023-03-15 05:53 UTC, merged