remove common types for chain
soramitsu/fearless-iOS pull request #936
Opened 2023-03-15 10:17 UTC by DRadmir

2023-03-15 10:54 UTC, bnsports requested changes

2023-03-15 10:54 UTC, bnsports commented on fearless/Common/Services/ChainRegistry/RuntimeProviderPool/RuntimeProviderPool.swift
> -        if let runtimeProvider = runtimeProviders[chain.chainId] {
please return cache using

2023-03-16 03:17 UTC, bnsports approved these changes

2023-03-16 04:44 UTC, Viscount88 approved these changes

2023-03-16 09:46 UTC, merged