Sora card phase 1
soramitsu/fearless-iOS pull request #939
Opened 2023-03-20 03:41 UTC by Viscount88

2023-03-20 07:31 UTC, bnsports requested changes

2023-03-20 07:31 UTC, bnsports commented on fearless/Modules/SoraCard/KYCOnboarding/KYCOnboardingPresenter.swift
> +            fatalError(NSLocalizedString("Camera Authorization Status not handled!", comment: "Status: \(AVCaptureDevice.authorizationStatus(for: .video))"))
please remove fatalError, it caused a crash on prod

2023-03-20 07:31 UTC, bnsports commented on fearless/Modules/SoraCard/KYCOnboarding/KYCOnboardingPresenter.swift
> +            return
not handled

2023-03-20 07:31 UTC, bnsports commented on fearless/Modules/SoraCard/KYCOnboarding/KYCOnboardingPresenter.swift
> +            fatalError(NSLocalizedString(
please remove fatalError

2023-03-20 08:03 UTC, DRadmir requested changes

2023-03-20 08:03 UTC, DRadmir commented on fearless/Modules/SoraCard/Preparation/PreparationViewLayout.swift
> +private extension PreparationViewLayout {
write methods in class body please

2023-03-20 08:03 UTC, DRadmir commented on fearless/Modules/SoraCard/Preparation/PreparationViewLayout.swift
> +    private func createSteps() -> [UIView] {
Needs create viewModelFactory for this method

2023-03-20 08:24 UTC, Viscount88 commented on fearless/ApplicationLayer/SoraCard/SCApiClient/SCApiClient.swift
> +            urlComponents.queryItems = (request.queryItems ?? []) + [URLQueryItem(name: "api_key", value: apiKey)]
removed, it's in SCService now

2023-03-20 08:25 UTC, Viscount88 commented on fearless/ApplicationLayer/SoraCard/SCService/SCKYCService.swift
> +        PayWingsOAuthClient.initialize(environmentType: .TEST, apiKey: apiKey, domain: domain)
we have only test api key for now

2023-03-20 08:31 UTC, Viscount88 commented on fearless/Common/Model/Chain.swift
> +//            Need to check
Checked, it's 1

2023-03-21 05:53 UTC, Viscount88 commented on fearless/Modules/SoraCard/VerificationStatus/ViewModel/VerificationStatusViewModelFactory.swift
> +            return .failure
because if you didn't start you have nothing to verify

2023-03-21 09:53 UTC, bnsports approved these changes

2023-03-21 10:50 UTC, DRadmir approved these changes

2023-03-21 11:03 UTC, merged