Feature/new stakings
soramitsu/fearless-iOS pull request #960
Opened 2023-04-12 09:50 UTC by bnsports

2023-04-13 06:30 UTC, Viscount88 submitted a review, later dismissed

2023-04-13 06:30 UTC, Viscount88 commented on fearless/Modules/Staking/StakingMain/StakingMainInteractor.swift
> +                let rewardChainAsset = chainAssets.first(where: { $0.asset.name.lowercased() == assetName.lowercased() }) ?? chainAsset
You already used that filter on fetch

2023-04-24 01:42 UTC, bnsports commented on fearless/Common/Services/PayoutRewardsService/PayoutValidatorForValidatorFactory.swift
>      ) -> CompoundOperationWrapper<[AccountId]> {
there are other implementations of this protocol with array as result

2023-04-24 02:38 UTC, DRadmir requested changes

2023-04-24 02:38 UTC, DRadmir commented on fearless/Modules/Staking/StakingMain/ViewModel/StakingStateViewModelFactory.swift
> +        let defaultReward: String = (chainAsset.chain.externalApi?.staking == nil) ? "N/A" : ""
use Locale for create default reward string

2023-04-24 02:38 UTC, DRadmir commented on fearless/Modules/Staking/StakingUnbondSetup/Flow/Parachain/StakingUnbondSetupParachainViewModelState.swift
> +            return ""
use uuid, to avoid fetch data from cache

2023-04-24 02:38 UTC, DRadmir commented on fearless/Modules/Staking/StakingUnbondSetup/Flow/Pool/StakingUnbondSetupPoolViewModelState.swift
> +            return ""
here too

2023-04-24 04:29 UTC, DRadmir approved these changes

2023-04-24 04:45 UTC, merged