FLW-3245 swap transaction details subscan added
soramitsu/fearless-iOS pull request #965
Opened 2023-04-20 01:05 UTC by bnsports

2023-04-20 01:23 UTC, Viscount88 commented on fearless/Modules/AllDone/AllDoneViewController.swift
>          rootView.subscanButton.isHidden = explorer == nil
I suggest group these buttons inside custom component with "func updateVisibility(for explorer: ChainModel.ExternalApiExplorer?)". Reuse this component for SwapTransactionDetail module

2023-04-20 01:23 UTC, Viscount88 commented on fearless/Modules/SwapTransactionDetail/SwapTransactionDetailRouter.swift
> +final class SwapTransactionDetailRouter: SwapTransactionDetailRouterInput {
Just use WebPresentable protocol. It's doing same thing.

2023-04-20 01:23 UTC, Viscount88 commented on fearless/Modules/SwapTransactionDetail/SwapTransactionDetailViewController.swift
> +        rootView.subscanButton.isHidden = explorer == nil
Reuse custom component here.

2023-04-20 01:23 UTC, Viscount88 commented on fearless/Modules/SwapTransactionDetail/SwapTransactionDetailViewLayout.swift
> +            make.height.equalTo(Constants.multiViewHeight)
I suggest use makeCommonConstraints(for: view) for defining height of each view)

2023-04-24 02:50 UTC, DRadmir requested changes

2023-04-24 02:50 UTC, DRadmir commented on fearless/Modules/SwapTransactionDetail/SwapTransactionDetailViewController.swift
> +    func didReceive(explorer: ChainModel.ExternalApiExplorer?) {
I suggest replace ChainModel.ExternalApiExplorer to Bool

2023-04-24 03:42 UTC, DRadmir approved these changes

2023-04-24 04:27 UTC, merged